<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>PortalStillAlive</RootNamespace>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(PublishAot)' == 'true'">
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>link</TrimMode>
        <OptimizationPreference>Size</OptimizationPreference>
        <InvariantGlobalization>true</InvariantGlobalization>
        <StackTraceSupport>false</StackTraceSupport>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(PublishAot)' == 'true' AND '$(RuntimeIdentifier)' == 'win-x64'">
        <PublishLzmaCompressed>true</PublishLzmaCompressed>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>
    
    <ItemGroup Condition="'$(PublishAot)' == 'true' AND '$(RuntimeIdentifier)' == 'win-x64'">
        <PackageReference Include="PublishAotCompressed" Version="1.0.5" />
    </ItemGroup>

    <ItemGroup Condition="'$(PublishAot)' == 'true'">
        <!-- This nuget package allows using Zig as the linker/sysroot to allow crosscompiling 
        to linux-x64/linux-arm64/linux-musl-x64/linux-musl-arm64 from a Windows machine.-->
        <PackageReference Include="PublishAotCross" Version="1.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="sa1.mp3">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
